name: Test

on:
  pull_request: {}
  push:
    branches:
      - master

env:
  BUNDLE_WITHOUT: release

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rake rubocop

  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - ruby: "2.7"
          - ruby: "3.0"
          - ruby: "3.1"
          - ruby: "3.2"
            coverage: "yes"
    env:
      COVERAGE: ${{ matrix.coverage }}
    name: RSpec - Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: set git config
        run: git config --global init.defaultBranch main && git config --global user.email 'user@example.com' && git config --global user.name 'user'
      - name: spec tests
        env:
          GIT_COMMITTER_NAME: 'user'
          GIT_COMMITTER_EMAIL: 'user@example.com'
          GIT_AUTHOR_NAME: 'user'
          GIT_AUTHOR_EMAIL: 'user@example.com'
        run: bundle exec rake
      - name: Verify gem builds
        run: gem build --strict --verbose *.gemspec

  tests:
    needs:
      - rubocop
      - rspec
    runs-on: ubuntu-latest
    name: Test suite
    steps:
      - run: echo Test suite completed
